name: Update upstream projects
on:
  push:
    branches:
      - master
      - '[0-9]+.[0-9]+'
jobs:
  dispatch:
    name: Dispatch a workflow event on upstream
    runs-on: ubuntu-latest
    steps:
      - name: Call github API
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.UPSTREAM_TOKEN }}" \
            https://api.github.com/repos/silimium/silimium/actions/workflows/downstream.yml/dispatches \
            -d '{"ref":"${{ GITHUB_SHA }}", "inputs":{"source":"${{ GITHUB_REPOSITORY }}","ref":"${{ GITHUB_REF }}"}}'
